### ISSUE TITLE
timeout param issue in mod::proxy

### ISSUE THREAD

**Issue by robertc99** [puppetlabs/puppetlabs-apache#2286]
Version 8 has set the type of apache::mod::proxy::proxy_timeout as undef or string. It should be undef or integer.
proxy_iobuffersize should probably also be integer.

**Comment by ekohl** [comment]
So this is:
https://github.com/puppetlabs/puppetlabs-apache/blob/92865b3d81dfd0895c60668b6f5db3e915a4e030/manifests/mod/proxy.pp#L33
The docs are https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxytimeout and those say it is in seconds, so `Integer` makes sense. Probably even `Integer[0]` since negative values are unsupported AFAIK.

Could you come up with a PR?

**Comment by ekohl** [comment]
Fixed in #2294
